# Generated by Django 4.0.4 on 2022-04-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_name_product_pname'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=200)),
                ('uemail', models.EmailField(max_length=200)),
                ('upass', models.CharField(max_length=200)),
                ('ucpass', models.CharField(max_length=200)),
            ],
        ),
    ]
